name: Build and Deploy Web App
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./metro_prototype

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # Build for web instead of APK
      - run: flutter build web --release
      
      # Upload the compiled web files
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: metro_prototype/build/web
          
